# Generated by Django 4.2 on 2023-04-15 17:06

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "iin",
                    models.CharField(
                        max_length=12,
                        unique=True,
                        validators=[core.models.validate_iin],
                        verbose_name="IIN",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Phone number"
                    ),
                ),
                ("password", models.CharField(max_length=30, verbose_name="Password")),
                ("is_staff", models.BooleanField(default=False, verbose_name="Admin")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=128, verbose_name="Region")),
                ("city", models.CharField(max_length=128, verbose_name="City")),
                ("street", models.CharField(max_length=128, verbose_name="Street")),
                (
                    "house_number",
                    models.CharField(max_length=128, verbose_name="House number"),
                ),
                (
                    "apartment",
                    models.CharField(max_length=128, verbose_name="Apartment"),
                ),
                ("entrance", models.CharField(max_length=128, verbose_name="Entrance")),
                ("floor", models.CharField(max_length=128, verbose_name="Floor")),
                ("block", models.CharField(max_length=128, verbose_name="Block")),
                (
                    "house_name",
                    models.CharField(max_length=128, verbose_name="House Name"),
                ),
                (
                    "additional_information",
                    models.TextField(
                        max_length=128, verbose_name="Additional information"
                    ),
                ),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firstname",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="First Name"
                    ),
                ),
                (
                    "middlename",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Middle Name"
                    ),
                ),
                (
                    "lastname",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Last Name"
                    ),
                ),
                (
                    "iin",
                    models.CharField(
                        max_length=12,
                        unique=True,
                        validators=[core.models.validate_iin],
                        verbose_name="IIN",
                    ),
                ),
                (
                    "home_address",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="Home Address"
                    ),
                ),
                (
                    "cashback",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=9,
                        verbose_name="Cashback",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Phone number",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
        migrations.CreateModel(
            name="CourierCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=128, unique=True, verbose_name="Name"),
                ),
            ],
            options={
                "verbose_name": "Courier company",
                "verbose_name_plural": "Courier companies",
            },
        ),
        migrations.CreateModel(
            name="ServiceCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.address",
                        verbose_name="Address",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Center",
                "verbose_name_plural": "Service Centers",
            },
        ),
        migrations.CreateModel(
            name="DocumentOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_name",
                    models.CharField(max_length=256, verbose_name="Service Name"),
                ),
                (
                    "request_id",
                    models.CharField(max_length=256, verbose_name="Request ID"),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Ready"),
                            (1, "Paid"),
                            (2, "Courier assigned"),
                            (3, "Courier on the way"),
                            (4, "Handed"),
                        ],
                        default=0,
                        verbose_name="Status",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="document_orders",
                        to="core.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "courier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="document_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Courier",
                    ),
                ),
                (
                    "delivery_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_address",
                        to="core.address",
                        verbose_name="Delivery Address",
                    ),
                ),
                (
                    "service_center",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="document_orders",
                        to="core.servicecenter",
                        verbose_name="Service Center",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Order",
                "verbose_name_plural": "Document Orders",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="courier_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="couriers",
                to="core.couriercompany",
                verbose_name="Courier company",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
