# Generated by Django 4.2 on 2023-04-15 08:11

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firstname",
                    models.CharField(max_length=128, verbose_name="First Name"),
                ),
                (
                    "lastname",
                    models.CharField(max_length=128, verbose_name="Last Name"),
                ),
                (
                    "iin",
                    models.CharField(
                        max_length=12,
                        validators=[core.models.validate_iin],
                        verbose_name="IIN",
                    ),
                ),
                (
                    "cashback",
                    models.DecimalField(
                        decimal_places=2, max_digits=9, verbose_name="Cashback"
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
    ]
