# Generated by Django 4.2 on 2023-04-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Admin"), (1, "Courier"), (2, "Service manager")],
                default=0,
                verbose_name="Status",
            ),
        ),
    ]
