# Generated by Django 4.2 on 2023-04-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="home_address",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="Home Address"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="middlename",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Middle Name"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="cashback",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=9, verbose_name="Cashback"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="firstname",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="First Name"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="lastname",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Last Name"
            ),
        ),
    ]
