# Generated by Django 4.2 on 2023-04-15 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="service_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_managers",
                to="core.servicecenter",
                verbose_name="Service center",
            ),
        ),
    ]
