# Generated by Django 4.2 on 2023-04-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_client_home_address_client_middlename_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_name",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Service Name"
                    ),
                ),
            ],
        ),
    ]
