# Generated by Django 4.2 on 2023-04-15 11:58

import core.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_documentorder_servicecenter"),
    ]

    operations = [
        migrations.CreateModel(
            name="Courier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Phone number"
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="documentorder",
            options={
                "verbose_name": "Document Order",
                "verbose_name_plural": "Document Orders",
            },
        ),
        migrations.AddField(
            model_name="client",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="Phone number",
            ),
        ),
        migrations.AddField(
            model_name="documentorder",
            name="client",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="document_orders",
                to="core.client",
                verbose_name="Client",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="documentorder",
            name="request_id",
            field=models.CharField(
                default=None, max_length=256, verbose_name="Apartment"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="documentorder",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Ready"),
                    (1, "Paid"),
                    (2, "Courier assigned"),
                    (3, "Courier on the way"),
                    (4, "Handed"),
                ],
                default=0,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="iin",
            field=models.CharField(
                max_length=12,
                unique=True,
                validators=[core.models.validate_iin],
                verbose_name="IIN",
            ),
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=128, verbose_name="Region")),
                ("city", models.CharField(max_length=128, verbose_name="City")),
                ("street", models.CharField(max_length=128, verbose_name="Street")),
                (
                    "house_number",
                    models.CharField(max_length=128, verbose_name="House number"),
                ),
                (
                    "apartment",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Apartment",
                    ),
                ),
                (
                    "entrance",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Entrance",
                    ),
                ),
                (
                    "floor",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Floor",
                    ),
                ),
                (
                    "block",
                    models.IntegerField(
                        blank=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Block",
                    ),
                ),
                (
                    "apartment_complex",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Apartment complex"
                    ),
                ),
                (
                    "additional_information",
                    models.TextField(
                        blank=True,
                        max_length=512,
                        verbose_name="Additional information",
                    ),
                ),
                (
                    "document_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="address",
                        to="core.documentorder",
                        verbose_name="Document order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.AddField(
            model_name="documentorder",
            name="courier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="document_orders",
                to="core.courier",
                verbose_name="Courier",
            ),
        ),
    ]
