# Generated by Django 4.2 on 2023-04-15 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_documentorder_client_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentorder",
            name="trusted_client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.client",
                verbose_name="Trusted client",
            ),
        ),
    ]
