# Generated by Django 4.2 on 2023-04-15 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_user_service_center"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentorder",
            name="delivery_datetime",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Delivery datetime"
            ),
            preserve_default=False,
        ),
    ]
