# Generated by Django 4.2 on 2023-04-15 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_documentorder_trusted_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentorder",
            name="courier_company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_orders",
                to="core.couriercompany",
                verbose_name="Courier Company",
            ),
        ),
    ]
