# Generated by Django 4.2 on 2023-04-15 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_documentorder_delivery_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentorder",
            name="delivery_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_address",
                to="core.address",
                verbose_name="Delivery Address",
            ),
        ),
    ]
