# Generated by Django 4.2 on 2023-04-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_courier_alter_documentorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentorder',
            name='request_id',
            field=models.CharField(max_length=256, verbose_name='Request ID'),
        ),
    ]
