# Generated by Django 4.2 on 2023-04-16 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_documentorder_courier_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="firstname",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="First Name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="lastname",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Last Name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="middlename",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Middle Name"
            ),
        ),
    ]
