# Generated by Django 4.2 on 2023-04-16 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_user_firstname_user_lastname_user_middlename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentorder",
            name="courier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Courier",
            ),
        ),
        migrations.AlterField(
            model_name="documentorder",
            name="courier_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_orders",
                to="core.couriercompany",
                verbose_name="Courier Company",
            ),
        ),
    ]
