# Generated by Django 4.2 on 2023-04-15 18:58

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_documentorder_delivery_datetime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="id",
        ),
        migrations.AlterField(
            model_name="user",
            name="iin",
            field=models.CharField(
                max_length=12,
                primary_key=True,
                serialize=False,
                unique=True,
                validators=[core.models.validate_iin],
                verbose_name="IIN",
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Pending"), (1, "Successful"), (2, "Failed")],
                        default=0,
                        verbose_name="Status",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="payments",
                        to="core.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "document_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="payment",
                        to="core.documentorder",
                        verbose_name="Document Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
            },
        ),
    ]
