# Generated by Django 4.2 on 2023-04-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_documentorder_courier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentorder",
            name="lat",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                default=None,
                max_digits=9,
                verbose_name="Latitude",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="documentorder",
            name="lng",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                default=None,
                max_digits=9,
                verbose_name="Longitude",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
