# Generated by Django 4.2 on 2023-04-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_documentorder_lat_documentorder_lng_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentorder",
            name="lat",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AlterField(
            model_name="documentorder",
            name="lng",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Longitude",
            ),
        ),
    ]
