# Generated by Django 4.2 on 2023-04-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_documentorder_lat_alter_documentorder_lng"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="additional_information",
            field=models.TextField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Additional information",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="apartment",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Apartment"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="block",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Block"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="entrance",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Entrance"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="floor",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Floor"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="house_name",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="House Name"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="house_number",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="House number"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="region",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Region"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="street",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Street"
            ),
        ),
    ]
