# Generated by Django 4.2 on 2023-04-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_address_additional_information_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="couriercompany",
            name="price_coefficient",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                default=1,
                max_digits=9,
                verbose_name="Price Coefficient",
            ),
            preserve_default=False,
        ),
    ]
