# Generated by Django 4.2 on 2023-04-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_couriercompany_price_coefficient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentorder",
            name="client_code",
            field=models.SmallIntegerField(
                blank=True, null=True, verbose_name="Client code"
            ),
        ),
    ]
